### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by robmcmullen** [peterferrie/standard-delivery#1]
I was interested in using the fstbt code to create a Python script to automatically generate a disk image. I didn't see a license in the code so I'm not sure if I can do that and follow the letter of the law. Would you mind adding a license or letting me fork it with permission? My code is open source: https://github.com/robmcmullen/atrcopy

**Comment by peterferrie** [comment]
Hi Rob,

> I was interested in using the fstbt code to create a Python script to
> automatically generate a disk image. I didn't see a license in the code so
> I'm not sure if I can do that and follow the letter of the law. Would you
> mind adding a license or letting me fork it with permission? My code is open
> source: https://github.com/robmcmullen/atrcopy

Thanks for asking.  I've added the license clause to the source files.
It's BSD-3.

**Comment by robmcmullen** [comment]
Great, thanks! I know nothing about disk access on the a2 so I could never have started from scratch. I've hacked around with it and got it to recognize some dummy values in adrtable to set HGR1 and HGR2 so it can will show images while loading. But I'm rapidly running out of bytes! I may have to implement some (count, start_page) hack in adrtable. I tried extending it to 2 sectors but the read order changed. I don't know what I'm doing. :)

**Comment by peterferrie** [comment]
> Great, thanks! I know nothing about disk access on the a2 so I could never
> have started from scratch. I've hacked around with it and got it to
> recognize some dummy values in adrtable to set HGR1 and HGR2 so it can will
> show images while loading. But I'm rapidly running out of bytes! I may have
> to implement some (count, start_page) hack in adrtable. I tried extending it
> to 2 sectors but the read order changed. I don't know what I'm doing. :)

Ah, that's not really the intention of that loader.  It's intended to
be a one-sector small one-shot loader.
If you need to load tons of stuff, you might consider 0boot (one-shot
loader but can load nearly 48kb), or qboot (loader that can be called
multiple times).
