### ISSUE TITLE
How to use standard-delivery?

### ISSUE THREAD

**Issue by wyatt-wong** [peterferrie/standard-delivery#2]
How do I put the compiled binary into Apple II disk file and use it for boot up ?

**Comment by peterferrie** [comment]
I use a sector editor for that job, and just copy/paste the content.

**Comment by wyatt-wong** [comment]
Do you have a disk already made up with the boot sector to share ?

**Comment by peterferrie** [comment]
The boot sector varies according to how much content is to be read.  You
can find examples in 4am's crack collection and via Passport.  Sirius
deprotection uses it.

**Comment by wyatt-wong** [comment]
I think you assume I am very knowledgeable in Apple II sector editing and know how to handle this kind of thing by myself. Sadly I don't know how to proceed on this. However said hat, I did manage to view the compiled binary and show it in HEX in Visual Studio Code, though I didn't know if the compiled binary is correct or not.

I used a Apple II Disk Editing tool and write the binary code into the track $00 sector $00 of a DOS 3.3 formatted DSK file and checked the DSK file was unable to boot up. So I am still wondering how to use the fstbt.s code

![Screenshot 2024-09-05 at 6 09 10 PM](https://github.com/user-attachments/assets/1716de68-6bc4-46c9-bc56-ef519768edac)

**Comment by peterferrie** [comment]
>
> I think you assume I am very knowledgeable in Apple II sector editing and
> know how to handle this kind of thing by myself.
>

That's the most basic requirement to use it, though.  Why do you want to
use this code?
Why not create, for example, a regular DOS disk with files on it?

**Comment by wyatt-wong** [comment]
> I think you assume I am very knowledgeable in Apple II sector editing and know how to handle this kind of thing by myself.
> That's the most basic requirement to use it, though. Why do you want to use this code? Why not create, for example, a regular DOS disk with files on it? Message ID: ***@***.***>
> […](#)

I found out this boot loader by accident so I would like to see how it works. Anyway, here is the DSK image I created. Please rename the file extension to .dsk

![bootloader](https://github.com/user-attachments/assets/e970b687-b909-4986-a2ab-2a9e1595be6a)

**Comment by peterferrie** [comment]
It's just loading sectors to addresses, one at a time.  It is not
efficient, but it is very flexible (any sector can be loaded to any
address).  You've managed to place the code correctly, but no content is
specified to be loaded so it will just break at $1234 if you boot that disk.

**Comment by wyatt-wong** [comment]
I am not sure how to write to $1234 and write what kind of file to that location. I reviewed the source and found that $1234 is an arbitrary address.

**Comment by peterferrie** [comment]
So, the idea is that your content is placed starting at track 0 sector 1 on
the disk, and the boot sector is updated to specify which sector goes where.
The $1234 should be replaced by the address of the first instruction to run
after the load is complete.
